-- CreateTable
CREATE TABLE `Sign` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `hashedSign` VARCHAR(255) NOT NULL,
    `date` DATETIME(3) NOT NULL,
    `userId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Sign` ADD CONSTRAINT `Sign_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
