import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ClassProvider } from "@/components/context/ClassContext";
import NavigationBar from "@/components/navigation/NavigationBar";
import { UserProvider } from "@/components/context/UserContext";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable + " bg-seasame"}>
        <UserProvider>
          <ClassProvider>
            <NavigationBar />
            {children}
          </ClassProvider>
        </UserProvider>
      </body>
    </html>
  );
}
