import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import React from "react";
import { ClassProvider } from "@/components/context/ClassContext";
import { SignatureProvider } from "@/components/context/SignatureContext";
import { Toaster } from "@/components/ui/toaster";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable + " bg-seasame h-full"}>
        <ClassProvider>
          <SignatureProvider>{children}</SignatureProvider>
          <Toaster />
        </ClassProvider>
      </body>
    </html>
  );
}
