name: CD Pipeline

on:
  push:
    branches:
      - main  # Déclenche le déploiement à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔄 Générer le client Prisma
        run: npx prisma generate

      - name: 🏗️ Appliquer les migrations Prisma
        run: npx prisma migrate deploy

      - name: 🎨 Vérification du formatage avec Prettier
        run: npx prettier --check .

      - name: 🔍 Vérification du code avec ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: 🏗️ Build Next.js app
        run: npm run build

      - name: 🚀 Déploiement sur Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
